spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yotsuba.mysql.database.azure.com:3306/project_football_pitch
    username: hieuhtt
    password: Thangchami269

    #image
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    #login gg
google:
  app:
    id: 59048210969-nd3uaoaoj85eu996p6vlu5338174ncb8.apps.googleusercontent.com
    secret: Jk5J817Ki1gP9QibueBfNcGo
  redirect:
    uri: http://localhost:8080/login-google
  link:
    get:
      token: https://accounts.google.com/o/oauth2/token
      scope: profile email
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?access_token=